name: Build and publish
# This workflow is triggered on new tags of Community Edition 7.8.x or later,
# or any of the weekly tag names starting 'master'
on:
  workflow_dispatch:

jobs:
  standard-build:
    name: "Build and publish release container"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./dockerfiles
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_user: ${{ secrets.BUILD_USER }}
          docker_repo: ${{ secrets.DOCKER_REPO }}
          latest: 0   # this should only be set on the current minor branch
          disable_cache: 0 #this should only be set to '1' if you want to disable the docker image cache


